import matplotlib.pyplot as plt
import numpy as np


#define given constants:
C_Dp = 0.0356
p = 1.225
AR = 8.75
S = 0.69
m = 5.3
g = 9.81
W = m * g

MAX_THRUST = 10
MAX_POWER = 200


def calc_C_L(velocity, lift, density, surface_area):
    return (lift * 2) / (density * velocity**2 * surface_area)

def calc_C_Di(C_L, aspect_ratio):
    return C_L**2/(np.pi * aspect_ratio)

def calc_P_D(density, velocity, C_D, surface_area):
    return 1/2 * density * velocity**3 * C_D * surface_area

if __name__ == "__main__":
    velocities = np.linspace(3, 30, 300)

    F_Dps, F_Dis, F_Ds, P_Ds = [], [], [], []

    for v in velocities:
        q_S = 0.5 * p * v**2 * S          # dynamic pressure times area
        C_L = calc_C_L(velocity=v, lift=W, density=p, surface_area=S)
        C_Di = calc_C_Di(C_L, AR)

        F_Dps.append(q_S * C_Dp)
        F_Dis.append(q_S * C_Di)
        F_Ds.append(q_S * (C_Dp + C_Di))

        P_Ds.append(calc_P_D(p, v, C_Dp + C_Di, S))

    F_Ds = np.array(F_Ds)
    P_Ds = np.array(P_Ds)

    # The following part was AI-generated by Claude Code:
    
    # Find where drag crosses the thrust limit
    thrust_crossings = np.where(
        np.diff(np.sign(F_Ds - MAX_THRUST)) != 0
    )[0]

    v_thrust = []

    for i in thrust_crossings:
        v1, v2 = velocities[i], velocities[i + 1]
        d1, d2 = F_Ds[i], F_Ds[i + 1]

        # Linear interpolation to find crossing velocity
        v_cross = v1 + (MAX_THRUST - d1) * (v2 - v1) / (d2 - d1)
        v_thrust.append(v_cross)

    # Find where power crosses the power limit
    power_crossings = np.where(
        np.diff(np.sign(P_Ds - MAX_POWER)) != 0
    )[0]

    v_power = []

    for i in power_crossings:
        v1, v2 = velocities[i], velocities[i + 1]
        p1, p2 = P_Ds[i], P_Ds[i + 1]

        # Linear interpolation to find crossing velocity
        v_cross = v1 + (MAX_POWER - p1) * (v2 - v1) / (p2 - p1)
        v_power.append(v_cross)

    print("Thrust limit velocities:", v_thrust)
    print("Power limit velocities:", v_power)

    plt.figure()
    plt.plot(velocities, F_Dis, label="Induced drag")
    plt.plot(velocities, F_Dps, label="Parasite drag")
    plt.plot(velocities, F_Ds, label="Total drag")

    plt.xlabel("Airspeed $v_\\infty$ [m/s]")
    plt.ylabel("Drag force [N]")
    plt.title("Drag force vs. airspeed")
    plt.axhline(MAX_THRUST, linestyle="--", label="Max thrust = 10 N")

    for v in v_thrust:
        plt.axvline(v, linestyle=":", label=f"v = {v:.2f} m/s")

    plt.legend()
    plt.grid(True)


    plt.figure()
    plt.plot(velocities, P_Ds, label="Drag power")

    plt.xlabel("Airspeed $v_\\infty$ [m/s]")
    plt.ylabel("Drag power [W]")
    plt.title("Drag power vs. airspeed")
    plt.axhline(MAX_POWER, linestyle="--", label="Max power = 200 W")

    for v in v_power:
        plt.axvline(v, linestyle=":", label=f"v = {v:.2f} m/s")

    plt.legend()
    plt.grid(True)


    plt.show()